export const queryKeys = {
  auth: {
    me: ["auth", "me"] as const,
  },
  markets: {
    all: (params?: unknown) => ["markets", "list", params] as const,
    detail: (address: string) => ["markets", "detail", address] as const,
    metrics: (address: string) => ["markets", "metrics", address] as const,
  },
  offers: {
    all: (params?: unknown) => ["offers", "list", params] as const,
    detail: (id: number) => ["offers", "detail", id] as const,
    quote: (params?: unknown) => ["offers", "quote", params] as const,
  },
  borrowers: {
    detail: (address: string) => ["borrowers", "detail", address] as const,
    risk: (address: string) => ["borrowers", "risk", address] as const,
  },
  positions: {
    all: (params?: unknown) => ["positions", "list", params] as const,
    detail: (tokenId: number) => ["positions", "detail", tokenId] as const,
    portfolio: ["positions", "portfolio"] as const,
  },
  withdrawals: {
    all: (params?: unknown) => ["withdrawals", "list", params] as const,
    epoch: ["withdrawals", "epoch"] as const,
  },
  auctions: {
    liquidations: (params?: unknown) => ["auctions", "liquidations", params] as const,
    detail: (id: number) => ["auctions", "detail", id] as const,
    price: (id: number) => ["auctions", "price", id] as const,
  },
  admin: {
    markets: (params?: unknown) => ["admin", "markets", params] as const,
    marketDetail: (address: string) => ["admin", "markets", "detail", address] as const,
    marketMetrics: (address: string) => ["admin", "markets", "metrics", address] as const,
    marketRisk: (address: string) => ["admin", "markets", "risk", address] as const,
    borrowers: (params?: unknown) => ["admin", "borrowers", params] as const,
    borrowerDetail: (address: string) => ["admin", "borrowers", "detail", address] as const,
    pendingBorrowers: ["admin", "borrowers", "pending"] as const,
    reputation: (address: string) => ["admin", "reputation", address] as const,
    defaultedBorrowers: ["admin", "reputation", "defaulted"] as const,
    health: ["admin", "health"] as const,
    auditLogs: (params?: Record<string, unknown>) => ["admin", "audit", "logs", params] as const,
    auditStats: ["admin", "audit", "stats"] as const,
    liquidatorConfig: ["admin", "liquidator", "config"] as const,
    liquidatorAuctions: ["admin", "liquidator", "auctions"] as const,
    protocolConfig: ["admin", "protocol", "config"] as const,
    systemConfig: ["admin", "system", "config"] as const,
    contractsStatus: ["admin", "contracts", "status"] as const,
    upgrades: ["admin", "upgrades", "pending"] as const,
    statsOverview: ["admin", "stats", "overview"] as const,
    statsBorrowers: ["admin", "stats", "borrowers"] as const,
    statsMarkets: ["admin", "stats", "markets"] as const,
    statsRevenue: ["admin", "stats", "revenue"] as const,
    statsLiquidations: ["admin", "stats", "liquidations"] as const,
    statsPositions: ["admin", "stats", "positions"] as const,
    admins: (params?: unknown) => ["admin", "admins", params] as const,
    feesCollected: ["admin", "fees", "collected"] as const,
  },
} as const;
